PATTERNS = {
    1: {
        "member_index": 0,
        "control_unit_list": [
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
        ],
        "period": 10000,
    },
}
