PATTERNS = {
    1: {
        "member_index": 0,
        "control_unit_list": [
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
            {"volumn": 10, "delay": 5},
        ],
        "period": 10000,
    },
    2: {
        "member_index": 0,
        "control_unit_list": [
            {"volumn": 10, "delay": 5},
            {"volumn": 11, "delay": 5},
            {"volumn": 12, "delay": 5},
            {"volumn": 13, "delay": 5},
            {"volumn": 14, "delay": 5},
            {"volumn": 15, "delay": 5},
            {"volumn": 16, "delay": 5},
            {"volumn": 17, "delay": 5},
            {"volumn": 18, "delay": 5},
            {"volumn": 19, "delay": 5},
            {"volumn": 20, "delay": 5},
            {"volumn": 21, "delay": 5},
            {"volumn": 22, "delay": 5},
            {"volumn": 23, "delay": 5},
            {"volumn": 24, "delay": 5},
            {"volumn": 25, "delay": 5},
            {"volumn": 26, "delay": 5},
            {"volumn": 27, "delay": 5},
            {"volumn": 28, "delay": 5},
            {"volumn": 29, "delay": 5},
            {"volumn": 30, "delay": 5},
            {"volumn": 31, "delay": 5},
            {"volumn": 32, "delay": 5},
            {"volumn": 33, "delay": 5},
            {"volumn": 34, "delay": 5},
            {"volumn": 35, "delay": 5},
            {"volumn": 36, "delay": 5},
            {"volumn": 37, "delay": 5},
            {"volumn": 38, "delay": 5},
            {"volumn": 39, "delay": 5},
            {"volumn": 40, "delay": 5},
            {"volumn": 41, "delay": 5},
            {"volumn": 42, "delay": 5},
            {"volumn": 43, "delay": 5},
            {"volumn": 44, "delay": 5},
            {"volumn": 45, "delay": 5},
            {"volumn": 46, "delay": 5},
            {"volumn": 47, "delay": 5},
            {"volumn": 48, "delay": 5},
        ],
        "period": 10000,
    },
    3: {
        "member_index": 0,
        "control_unit_list": [
            {"volumn": 20, "delay": 0 },
            {"volumn": 20, "delay": 1 },
            {"volumn": 20, "delay": 2 },
            {"volumn": 20, "delay": 3 },
            {"volumn": 20, "delay": 4 },
            {"volumn": 20, "delay": 5 },
            {"volumn": 20, "delay": 6 },
            {"volumn": 20, "delay": 7 },
            {"volumn": 20, "delay": 8 },
            {"volumn": 20, "delay": 9 },
            {"volumn": 20, "delay": 10},
            {"volumn": 20, "delay": 11},
            {"volumn": 20, "delay": 12},
            {"volumn": 20, "delay": 13},
            {"volumn": 20, "delay": 14},
            {"volumn": 20, "delay": 15},
            {"volumn": 20, "delay": 16},
            {"volumn": 20, "delay": 17},
            {"volumn": 10, "delay": 18},
            {"volumn": 10, "delay": 19},
            {"volumn": 10, "delay": 20},
            {"volumn": 10, "delay": 21},
            {"volumn": 10, "delay": 22},
            {"volumn": 10, "delay": 23},
            {"volumn": 10, "delay": 24},
            {"volumn": 10, "delay": 25},
            {"volumn": 10, "delay": 26},
            {"volumn": 10, "delay": 27},
            {"volumn": 10, "delay": 28},
            {"volumn": 10, "delay": 29},
            {"volumn": 10, "delay": 30},
            {"volumn": 10, "delay": 31},
            {"volumn": 10, "delay": 32},
            {"volumn": 10, "delay": 33},
            {"volumn": 10, "delay": 34},
            {"volumn": 10, "delay": 35},
            {"volumn": 10, "delay": 36},
            {"volumn": 10, "delay": 37},
            {"volumn": 10, "delay": 38},
        ],
        "period": 10000,
    },
}
